LABEL_MAPPING = {
    "tumor_area": 0,
    "non_tumor_area": 1,
    "cancer_ducts": 2,
    "normal_ducts": 3,
    "islets": 4,
    "nerves": 5,
    "lymfocytic_infiltrate": 6,
    "vessels": 7,
    "fat": 8,
    "atrophic_metaplastic_parenchyma": 9,
    "acinic_tissue": 10,
    "mucinous_dissection": 11,
    "uncertain": 12,
    "duodenum": 13,
    "ignore": 14,
    "in_situ_neoplasia": 15,
    "lumen": 16,
}
